server:
  port: 9001
spring:
  application:
    name: server-message
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    database: mysql
    hibernate:
      # create：每次加载 Hibernate 时都会删除上一次生成的表，然后根据 model 类再重新来生成新表，哪怕两次没有任何改变也要这样执行，这就是导致数据库表数据丢失的一个重要原因。
      # create-drop：每次加载 Hibernate 时根据 model 类生成表，但是 sessionFactory 一关闭，表就自动删除。
      # update：最常用的属性，第一次加载 Hibernate 时根据 model 类会自动建立起表的结构，以后加载 Hibernate 时根据 model 类自动更新表结构，不会删除表中的数据。
      # validate ：每次加载 Hibernate 时，验证创建数据库表结构，只会和数据库中的表进行比较，不会创建新表，但是会插入新值。
      ddl-auto: update
    # 打印SQL
    show-sql: true
    # 指定自动创建表时使用 InnoDB 引擎，默认是 MyISAM
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
rocketmq:
  name-server: 192.168.10.252:9876 # 指定 RocketMQ 服务地址