server:
  port: 8071
spring:
  application:
    name: service-user
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    database: mysql
    hibernate:
      # create：每次加载 Hibernate 时都会删除上一次生成的表，然后根据 model 类再重新来生成新表，哪怕两次没有任何改变也要这样执行，这就是导致数据库表数据丢失的一个重要原因。
      # create-drop：每次加载 Hibernate 时根据 model 类生成表，但是 sessionFactory 一关闭，表就自动删除。
      # update：最常用的属性，第一次加载 Hibernate 时根据 model 类会自动建立起表的结构，以后加载 Hibernate 时根据 model 类自动更新表结构，不会删除表中的数据。
      # validate ：每次加载 Hibernate 时，验证创建数据库表结构，只会和数据库中的表进行比较，不会创建新表，但是会插入新值。
      ddl-auto: update
    # 打印SQL
    show-sql: true
    # 指定自动创建表时使用 InnoDB 引擎，默认是 MyISAM
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#rocketmq:
#  name-server: 192.168.10.252:9876 # 指定 RocketMQ 服务地址

#seata配置
seata:
  enabled: true
  application-id: ${spring.application.name}
  #这里的名字与file.conf中vgroup_mapping.service-order-group = "default"相同
  tx-service-group: service-order-group
  enable-auto-data-source-proxy: true
  #  use-jdk-proxy: false
  service:
    #这里的名字与file.conf中vgroup_mapping.service-order-group = "default"相同
    vgroup-mapping:
      service-order-group: default
      #这里的名字与file.conf中default.grouplist = "127.0.0.1:8091"相同
  #    grouplist:
  #      default: 127.0.0.1:8091
  #      disable-global-transaction: false
  config:
    type: nacos
    nacos:
      namespace:
      #这里的地址就是你的nacos的地址,可以更换为线上
      serverAddr: localhost:8848
      #这里的名字就是registry.conf中 nacos的group名字
      group: SEATA_GROUP
      userName: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      #这里的地址就是你的nacos的地址,可以更换为线上
      server-addr: localhost:8848
      #这里的名字就是registry.conf中 nacos的group名字
      group: SEATA_GROUP
      namespace:
      userName: "nacos"
      password: "nacos"